// <auto-generated />
namespace Mohawk.Executive.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedResolutionFunctionality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedResolutionFunctionality));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051852523_AddedResolutionFunctionality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
